# Generated by Django 5.0.3 on 2024-04-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_event_type_alter_event_specializations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("registration is open", "регистрация открыта"),
                    ("registration offline is closed", "регистрация офлайн закрыта"),
                    ("registration online is closed", "регистрация онлайн закрыта"),
                    ("registration is closed", "регистрация закрыта"),
                ],
                default="registration is open",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
    ]
