# Generated by Django 5.0.3 on 2024-04-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="participant_offline_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Максимальное количество участников в формате офлайн",
                null=True,
                verbose_name="Офлайн-лимит",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="participant_online_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Максимальное количество участников в формате онлайн",
                null=True,
                verbose_name="Онлайн-лимит",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Предельный срок (дата и время) регистрации на участие в мероприятии",
                null=True,
                verbose_name="Регистрация до",
            ),
        ),
    ]
