# Generated by Django 5.0.4 on 2024-04-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_city_event_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventpart",
            name="is_deleted",
        ),
        migrations.AlterField(
            model_name="event",
            name="is_deleted",
            field=models.BooleanField(default=True, verbose_name="Деактивировано"),
        ),
    ]
