# Generated by Django 5.0.4 on 2024-04-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_remove_eventpart_is_deleted_alter_event_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpart",
            name="presentation_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Тип"
            ),
        ),
    ]
