# Generated by Django 5.0.3 on 2024-04-06 04:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Создано"
            ),
        ),
    ]
