# Generated by Django 5.0.4 on 2024-04-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_application_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="activity",
            field=models.CharField(
                choices=[
                    ("working", "работаю"),
                    ("studying", "учусь"),
                    ("seeking", "в поиске работы"),
                ],
                max_length=20,
                verbose_name="Род занятий",
            ),
        ),
    ]
